"""Application service layer wrappers."""

from green_direct.services.job_store import LocalJobStore
from green_direct.services.pilot_access import PilotAccessError, PilotAccessService
from green_direct.services.pilot_admin import LocalPilotAdminService, PilotAdminError
from green_direct.services.pilot_auth import (
    LocalPilotAuth,
    PilotAuthError,
    PilotLoginSession,
    PilotSessionRecord,
)
from green_direct.services.pilot_registry import LocalPilotRegistry
from green_direct.services.pilot_study_persistence import (
    PersistedEconomicStudy,
    PersistedAnnualCashflowArtifact,
    PersistedExportArtifact,
    PersistedHourlyDetailArtifact,
    PersistedRecommendationStudy,
    PersistedTechnicalStudy,
    QueuedJobWithInputArtifact,
    economic_input_fingerprint,
    persist_economic_study_result,
    persist_annual_cashflow_artifact,
    persist_export_artifact,
    persist_hourly_detail_artifact,
    persist_recommendation_study_result,
    persist_technical_study_result,
    queue_job_with_input_artifact,
    recommendation_result_fingerprint,
    technical_input_fingerprint,
)
from green_direct.services.pilot_store_doctor import (
    PilotStoreDoctorCheck,
    PilotStoreDoctorResult,
    run_pilot_store_doctor,
)
from green_direct.services.pilot_support_bundle import build_pilot_support_bundle
from green_direct.services.pilot_worker import (
    PilotWorkerExecutionResult,
    PilotWorkerLoopResult,
    execute_claimed_worker_job,
    execute_next_worker_job,
    execute_worker_loop,
)
from green_direct.services.result_store import LocalResultStore
from green_direct.services.study_runner import (
    EconomicStudyResult,
    RecommendationInputSnapshot,
    RecommendationStudyResult,
    StudyResult,
    TechnicalStudyInput,
    TechnicalStudyResult,
    build_recommendation_study,
    run_hourly_detail_for_scenario,
    run_economic_study,
    run_technical_study,
    scenario_from_summary_row,
)
from green_direct.services.upload_policy import (
    DEFAULT_MAX_UPLOAD_BYTES,
    UploadFileInfo,
    UploadPolicy,
    UploadValidationError,
    filter_uploads,
    inspect_upload,
)

__all__ = [
    "EconomicStudyResult",
    "LocalJobStore",
    "LocalPilotAdminService",
    "LocalPilotAuth",
    "LocalPilotRegistry",
    "LocalResultStore",
    "PilotAccessError",
    "PilotAuthError",
    "PilotAccessService",
    "PilotAdminError",
    "PilotLoginSession",
    "PilotSessionRecord",
    "PilotStoreDoctorCheck",
    "PilotStoreDoctorResult",
    "PilotWorkerExecutionResult",
    "PilotWorkerLoopResult",
    "PersistedEconomicStudy",
    "PersistedAnnualCashflowArtifact",
    "PersistedExportArtifact",
    "PersistedHourlyDetailArtifact",
    "PersistedRecommendationStudy",
    "PersistedTechnicalStudy",
    "QueuedJobWithInputArtifact",
    "RecommendationInputSnapshot",
    "RecommendationStudyResult",
    "StudyResult",
    "TechnicalStudyInput",
    "TechnicalStudyResult",
    "DEFAULT_MAX_UPLOAD_BYTES",
    "UploadFileInfo",
    "UploadPolicy",
    "UploadValidationError",
    "build_recommendation_study",
    "build_pilot_support_bundle",
    "economic_input_fingerprint",
    "execute_claimed_worker_job",
    "execute_next_worker_job",
    "execute_worker_loop",
    "filter_uploads",
    "inspect_upload",
    "persist_economic_study_result",
    "persist_annual_cashflow_artifact",
    "persist_export_artifact",
    "persist_hourly_detail_artifact",
    "persist_recommendation_study_result",
    "persist_technical_study_result",
    "queue_job_with_input_artifact",
    "recommendation_result_fingerprint",
    "run_pilot_store_doctor",
    "run_hourly_detail_for_scenario",
    "run_economic_study",
    "run_technical_study",
    "scenario_from_summary_row",
    "technical_input_fingerprint",
]
